export const site = {
  name: 'Titan Storm Roofing',
  tagline: 'When the Storm Hits, We\'re Already on the Way.',
  phone: '(469) 555-0187',
  phoneHref: 'tel:+14695550187',
  emergencyPhone: '(469) 555-0199',
  emergencyPhoneHref: 'tel:+14695550199',
  email: 'info@titanstormroofing.com',
  address: '8350 N Central Expy, Suite 200, Dallas, TX 75206',
  hours: 'Mon–Sat 6am–8pm, Sun Emergency Only',
  serviceAreas: [
    'Dallas', 'Plano', 'Frisco', 'McKinney',
    'Allen', 'Richardson', 'Garland', 'Mesquite',
    'Irving', 'Arlington', 'Fort Worth', 'Denton',
  ],
  stats: [
    { value: '15+', label: 'Years in DFW' },
    { value: '3,000+', label: 'Roofs Replaced' },
    { value: '24/7', label: 'Emergency Response' },
    { value: '$0', label: 'Out-of-Pocket (Insurance)' },
  ],
  credentials: ['GAF MASTER ELITE', 'BBB A+', 'HAAG CERTIFIED', 'TX LIC #RF-28491'],
  services: [
    {
      title: 'Storm Damage Restoration',
      slug: 'storm-damage',
      description: 'Hail ripped through your neighborhood and every roofer in town is booked. Not us. We deploy within hours, document every square inch of damage, and fight your insurance company so you don\'t have to.',
      image: 'https://images.unsplash.com/photo-1523772354886-34a1dc2f0285?w=800&q=80',
      features: ['Rapid 24-hour deployment', 'Full damage documentation with drone imagery', 'Direct insurance negotiation', 'Temporary tarping included', 'Zero upfront cost on approved claims'],
    },
    {
      title: 'Residential Re-Roofing',
      slug: 'residential',
      description: 'Your roof is 20 years old and it shows. We tear it down to the deck, fix what\'s rotting underneath, and install a roof system that laughs at Texas weather for the next three decades.',
      image: 'https://images.unsplash.com/photo-1632759145351-1d592919f522?w=800&q=80',
      features: ['Complete tear-off to decking', 'Rot and deck repair included', 'GAF Timberline HDZ shingles', 'Ice and water shield at all penetrations', 'Lifetime workmanship warranty'],
    },
    {
      title: 'Commercial Flat Roofs',
      slug: 'commercial',
      description: 'Flat roofs fail when contractors cut corners. We don\'t. TPO, EPDM, modified bitumen — we install commercial systems that hold up under brutal DFW summers and pass every inspection.',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
      features: ['TPO and EPDM membrane systems', 'Modified bitumen installs', 'Preventive maintenance contracts', 'Roof coating and restoration', 'Code-compliant drainage solutions'],
    },
    {
      title: 'Emergency Tarping & Repair',
      slug: 'emergency',
      description: 'Tree through your roof at 2 AM? We answer the phone. Our emergency crew gets a tarp on fast, stops the water, and prevents thousands more in interior damage. Every minute counts.',
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
      features: ['24/7 emergency dispatch', 'On-site within 2 hours', 'Heavy-duty tarp installation', 'Interior water mitigation referrals', 'Same-week permanent repair scheduling'],
    },
    {
      title: 'Insurance Claims Assistance',
      slug: 'insurance',
      description: 'Insurance companies lowball. We don\'t let them. Our claims team meets your adjuster on-site, documents every line item, and fights for the full replacement your policy covers.',
      image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
      features: ['Free adjuster meeting on-site', 'Line-item Xactimate estimates', 'Supplement filing for underpayments', 'Policy review and coverage guidance', '$0 out-of-pocket on approved claims'],
    },
  ],
  testimonials: [
    {
      text: 'A massive hailstorm tore up half our street. Titan Storm was on our roof the next morning while other companies were still "scheduling estimates." They handled the entire insurance claim and we paid nothing out of pocket. Absolute professionals.',
      author: 'Marcus & Linda J.',
      location: 'Plano, TX',
      rating: 5,
    },
    {
      text: 'Had a tree limb punch through our roof during a thunderstorm at midnight. Called Titan Storm and they had a crew out within 90 minutes to tarp it. The permanent repair was done three days later. These guys are the real deal.',
      author: 'Derek S.',
      location: 'Frisco, TX',
      rating: 5,
    },
    {
      text: 'Three different roofers told me I only needed repairs. Titan Storm showed me drone footage of damage the others completely missed. Got a full replacement covered by insurance. Saved me from a roof collapse I didn\'t even know was coming.',
      author: 'Rachel M.',
      location: 'McKinney, TX',
      rating: 5,
    },
  ],
  social: {
    google: '#',
  },
  gallery: [
    { title: 'Storm Damage Restoration', type: 'STORM REPAIR', image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80' },
    { title: 'Full Roof Replacement — Plano', type: 'FULL REPLACEMENT', image: 'https://images.unsplash.com/photo-1632759145351-1d592919f522?w=600&q=80' },
    { title: 'Commercial TPO Install', type: 'COMMERCIAL', image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80' },
    { title: 'Emergency Tarp — McKinney', type: 'EMERGENCY', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80' },
    { title: 'Residential Re-Roof — Frisco', type: 'FULL REPLACEMENT', image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80' },
    { title: 'Hail Damage Assessment', type: 'STORM REPAIR', image: 'https://images.unsplash.com/photo-1523772354886-34a1dc2f0285?w=600&q=80' },
  ],
}
