export const site = {
  name: 'Apex Roofing Co.',
  tagline: 'Built to Last. Backed by Decades of Experience.',
  phone: '(312) 555-0192',
  phoneHref: 'tel:+13125550192',
  email: 'info@apexroofingco.com',
  address: '4820 W Irving Park Rd, Chicago, IL 60641',
  hours: 'Mon–Sat 7 AM – 6 PM',
  serviceAreas: [
    'Chicago', 'Evanston', 'Oak Park', 'Cicero',
    'Berwyn', 'Skokie', 'Schaumburg', 'Naperville',
    'Arlington Heights', 'Des Plaines', 'Park Ridge', 'Elmhurst',
  ],
  services: [
    {
      title: 'Roof Replacement',
      slug: 'replacement',
      short: 'Complete tear-off and replacement with premium materials and ironclad warranties.',
      description: 'When repairs aren\'t enough, we handle full roof replacements from tear-off to final inspection. We use top-tier shingles from GAF and CertainTeed, and every install comes with a workmanship warranty you can count on.',
      features: ['Full tear-off & disposal', 'GAF & CertainTeed shingles', 'Ice & water shield protection', 'Proper ventilation install', '25-year workmanship warranty', 'Insurance claim assistance'],
      image: 'https://images.unsplash.com/photo-1632759145351-1d592919f522?w=600&q=80',
    },
    {
      title: 'Roof Repair',
      slug: 'repair',
      short: 'Fast, permanent fixes for leaks, storm damage, and worn-out sections.',
      description: 'Leaking roof? Missing shingles after a storm? We diagnose the real problem and fix it right the first time — no temporary patches that fail next season.',
      features: ['Leak detection & repair', 'Storm damage restoration', 'Shingle replacement', 'Flashing repair', 'Emergency tarping', 'Detailed damage reports'],
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80',
    },
    {
      title: 'Gutters & Drainage',
      slug: 'gutters',
      short: 'Seamless gutter install, repair, and leaf guard systems to protect your foundation.',
      description: 'Your gutters are your roof\'s first line of defense. We install seamless aluminum gutters, downspout extensions, and leaf guard systems that keep water moving away from your home.',
      features: ['Seamless aluminum gutters', 'Leaf guard installation', 'Downspout extensions', 'Gutter cleaning & repair', 'French drain systems', 'Ice dam prevention'],
      image: 'https://images.unsplash.com/photo-1585544314038-a0d3769d0193?w=600&q=80',
    },
    {
      title: 'Siding & Exterior',
      slug: 'siding',
      short: 'Vinyl, fiber cement, and wood siding that transforms your home\'s curb appeal.',
      description: 'A new roof deserves a fresh exterior. We install and repair vinyl, James Hardie fiber cement, and engineered wood siding — plus soffit, fascia, and trim work.',
      features: ['Vinyl siding install', 'James Hardie fiber cement', 'Soffit & fascia replacement', 'Trim & accent work', 'Color consultation', 'Full exterior remodel'],
      image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80',
    },
    {
      title: 'Inspections & Maintenance',
      slug: 'inspections',
      short: 'Annual inspections and preventive maintenance that catch problems before they cost you.',
      description: 'The cheapest roof repair is the one you never need. Our inspection program catches cracked flashing, lifted shingles, and drainage issues before they become interior water damage.',
      features: ['21-point roof inspection', 'Drone aerial assessment', 'Moisture detection scanning', 'Annual maintenance plans', 'Real estate inspections', 'Detailed photo reports'],
      image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80',
    },
    {
      title: 'Commercial Roofing',
      slug: 'commercial',
      short: 'Flat roof systems, TPO, EPDM, and metal roofing for businesses and multi-unit properties.',
      description: 'We handle commercial projects of every scale — from single-story retail to multi-unit residential. Our crew is certified in TPO, EPDM, and standing seam metal systems.',
      features: ['TPO & EPDM systems', 'Standing seam metal', 'Built-up roofing (BUR)', 'Roof coatings & restoration', 'Preventive maintenance contracts', 'Emergency commercial repair'],
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80',
    },
  ],
  social: {
    google: '#',
  },
  testimonials: [
    {
      text: 'We had three companies come out after the hailstorm. Apex was the only one who walked us through the entire insurance process and didn\'t pressure us into signing on the spot. The new roof looks incredible and the crew left our yard cleaner than they found it.',
      author: 'Jennifer & Mark T.',
      location: 'Oak Park, IL',
      rating: 5,
    },
    {
      text: 'These guys are the real deal. Found a leak that two other roofers missed completely. Fixed it in one visit, fair price, and it hasn\'t leaked since. That was two winters ago.',
      author: 'Carlos R.',
      location: 'Chicago, IL',
      rating: 5,
    },
    {
      text: 'Had our entire roof and gutters replaced. The team was professional from the estimate through final cleanup. They even replaced some rotted fascia boards they found during tear-off at no extra charge. That\'s integrity.',
      author: 'Diane W.',
      location: 'Evanston, IL',
      rating: 5,
    },
  ],
}
