export const site = {
  name: 'Dobbins Electric Co.',
  tagline: "Tulsa's Licensed Master Electricians Since 1998",
  phone: '(918) 555-0173',
  phoneHref: 'tel:+19185550173',
  emergencyPhone: '(918) 555-0199',
  emergencyPhoneHref: 'tel:+19185550199',
  email: 'service@dobbinselectric.com',
  address: '2847 E Admiral Pl, Tulsa, OK 74110',
  hours: 'Mon–Fri 7am–6pm, Sat 8am–2pm',
  license: 'OK Master #ME-18847',
  serviceAreas: [
    'Tulsa', 'Broken Arrow', 'Owasso', 'Bixby',
    'Jenks', 'Sand Springs', 'Sapulpa', 'Claremore',
    'Catoosa', 'Glenpool', 'Coweta', 'Collinsville',
  ],
  stats: [
    { value: '26+', label: 'Years Licensed' },
    { value: '8,400+', label: 'Jobs Completed' },
    { value: '24/7', label: 'Emergency Service' },
    { value: '100%', label: 'Code Compliant' },
  ],
  credentials: ['OK MASTER ELECTRICIAN', 'BBB A+', 'FULLY INSURED', 'LIC #ME-18847'],
  services: [
    {
      title: 'Residential Wiring',
      slug: 'residential',
      description: 'From whole-house rewires on 1960s knob-and-tube to new construction rough-ins, we handle every wire, breaker, and outlet in your home. Everything passes inspection the first time because we do it right the first time.',
      image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80',
      features: ['Whole-house rewiring', 'Panel upgrades to 200A', 'Outlet and switch installation', 'Ceiling fan and fixture wiring', 'Code violation corrections'],
    },
    {
      title: 'Commercial Electrical',
      slug: 'commercial',
      description: 'Restaurants, offices, warehouses — we wire them all. Three-phase service, high-voltage feeds, data cabling, and commercial lighting designed to keep your business running and your energy bills down.',
      image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
      features: ['Three-phase installations', 'Commercial lighting design', 'Tenant build-outs', 'Energy audits and retrofits', 'Generator transfer switches'],
    },
    {
      title: 'Panel Upgrades',
      slug: 'panels',
      description: 'Your 100-amp panel from the Carter administration cannot handle a modern kitchen, an EV charger, and central air at the same time. We upgrade your electrical panel so your home can keep up with how you actually live.',
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
      features: ['100A to 200A upgrades', 'Sub-panel installations', 'Meter base replacements', 'Whole-home surge protection', 'Federal Pacific and Zinsco replacements'],
    },
    {
      title: 'EV Charger Installation',
      slug: 'ev-chargers',
      description: 'Level 2 charger in your garage, wired to code and ready to charge overnight. We handle the permit, run the circuit, mount the unit, and make sure your panel can support it without tripping everything else in the house.',
      image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80',
      features: ['Level 2 (240V) installations', 'Tesla, ChargePoint, JuiceBox compatible', 'Panel load calculations', 'Permit and inspection handling', 'NEMA 14-50 outlet option'],
    },
    {
      title: 'Emergency Electrical',
      slug: 'emergency',
      description: 'Sparking outlet at midnight? Breaker that will not reset? Power out in half the house? Call the emergency line. A licensed electrician picks up — not an answering service — and we are at your door fast.',
      image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
      features: ['24/7 emergency dispatch', 'Sparking and burning smell calls', 'Breaker and fuse failures', 'Power outage diagnostics', 'Storm damage repair'],
    },
  ],
  testimonials: [
    {
      text: 'Our 1972 ranch had the original wiring and a panel that scared every inspector who looked at it. Dobbins rewired the entire house in four days, passed inspection on the first try, and left the place cleaner than they found it. Worth every penny.',
      author: 'Karen & Bill T.',
      location: 'Broken Arrow, OK',
      rating: 5,
    },
    {
      text: 'Had a burning smell coming from an outlet at 11 PM on a Saturday. Called Dobbins and a real electrician answered, not some call center. He was at our house in under an hour and found a connection that was about to start a fire. These guys saved our home.',
      author: 'James R.',
      location: 'Tulsa, OK',
      rating: 5,
    },
    {
      text: 'Needed a Level 2 charger for my Model Y and two other electricians said my panel could not handle it. Dobbins upgraded my panel to 200 amps and had the charger installed in one day. Charges overnight, no issues. Exactly what was promised.',
      author: 'Priya S.',
      location: 'Jenks, OK',
      rating: 5,
    },
  ],
  social: {
    google: '#',
  },
  gallery: [
    { title: 'Full House Rewire — Broken Arrow', type: 'RESIDENTIAL', image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80' },
    { title: '200A Panel Upgrade', type: 'PANEL', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80' },
    { title: 'Commercial Tenant Build-Out', type: 'COMMERCIAL', image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80' },
    { title: 'Tesla Wall Connector Install', type: 'EV CHARGER', image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&q=80' },
    { title: 'Outdoor Landscape Lighting', type: 'RESIDENTIAL', image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80' },
    { title: 'Emergency Panel Repair', type: 'EMERGENCY', image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80' },
  ],
}
